Discord:
  BotToken: YOUR_BOT_TOKEN
Network:
  Proxy:
    Enabled: false
    Host: YOUR_PROXY_HOST
Modules:
  OpenExchangeRate:
    AppId: YOUR_OPEN_EXCHANGE_RATE_APP_ID
    Plan: Free
    ForceUpdate:
      Currencies: 30d
      ExchangeRates: 1h
